# Generated by Django 4.0.7 on 2023-04-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('photo_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
