# Generated by Django 4.0.7 on 2023-04-18 18:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Breed must be greater than 1 character')])),
            ],
        ),
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='cat',
            name='foods',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='nickname',
            field=models.CharField(default='bob', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='weight',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cats.breed'),
            preserve_default=False,
        ),
    ]
